# Generated by Django 3.2.17 on 2023-02-07 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hospede', models.CharField(max_length=200)),
                ('numero_quarto', models.CharField(max_length=200)),
                ('valor_quarto', models.FloatField()),
                ('valor_comanda', models.FloatField()),
                ('diarias', models.IntegerField()),
                ('data_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_entrada', models.DateTimeField(blank=True)),
                ('data_saida', models.DateTimeField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
