# Generated by Django 3.2.17 on 2023-02-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedado',
            name='estatus',
            field=models.CharField(default='reservado', max_length=200),
        ),
    ]
