# Generated by Django 3.2.17 on 2023-02-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospedado_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospedado',
            old_name='estatus',
            new_name='status',
        ),
    ]
