# Generated by Django 3.2.17 on 2023-02-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20230208_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
