# Generated by Django 3.2.17 on 2023-02-10 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_hospede_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospede',
            old_name='status',
            new_name='habilitato',
        ),
    ]
