# Generated by Django 3.2.17 on 2023-02-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_status_hospede_habilitato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospede',
            old_name='habilitato',
            new_name='habilitado',
        ),
    ]
