# Generated by Django 3.2.17 on 2023-02-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_quarto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamento_conta',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quarto',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
