# Generated by Django 3.2.17 on 2023-02-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_auto_20230210_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='pessoas_suporta',
        ),
        migrations.AddField(
            model_name='quarto',
            name='capacidade',
            field=models.IntegerField(default=0),
        ),
    ]
