# Generated by Django 3.2.17 on 2023-02-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230210_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_entrada',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_saida',
            field=models.DateField(blank=True),
        ),
    ]
