# Generated by Django 3.2.17 on 2023-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230213_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_entrada',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_saida',
            field=models.DateTimeField(blank=True),
        ),
    ]
