# Generated by Django 3.2.17 on 2023-02-13 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230213_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_entrada',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_saida',
            field=models.DateField(blank=True),
        ),
    ]
