# Generated by Django 3.2.17 on 2023-02-14 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_reserva_datas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='datas',
        ),
    ]
