# Generated by Django 3.2.17 on 2023-02-15 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_remove_reserva_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedes_reserva',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Reserva_pendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('habilitado', models.BooleanField(default=True)),
                ('data_entrada', models.DateField(blank=True)),
                ('data_saida', models.DateField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
