# Generated by Django 3.2.17 on 2023-02-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230215_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva_pendente',
            name='quantidade_hospedes',
            field=models.IntegerField(default=0),
        ),
    ]
