# Generated by Django 3.2.17 on 2023-02-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_auto_20230217_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='diarias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='valor',
            field=models.FloatField(),
        ),
    ]
