# Generated by Django 3.2.17 on 2023-02-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_reserva_quantidade_hospedes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedes_reserva',
            name='status',
            field=models.CharField(default='EM ABERTO', max_length=200),
        ),
    ]
